
server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb+srv://rohan:12345@cluster0.x4viu.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name : Customer-Service
  main:
   allow:
    circular:
      references: true
